spring:
    cloud:
        stream:
            function:
                definition: transform|filterFunction
                bindings:
                    transformfilterFunction-out-0: output
                    transformfilterFunction-in-0: input

filter:
    function:
        expression: headers[usage]=='true'

